server:
  port: 9009

spring:
  application:
    name: admin-bff

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

consumer:
  failed-event-services:
    - notification-service
    - inventory-service
    - search-service

  services:
    notification: notification-service
    auth: auth-service
    inventory: inventory-service
  timeout: 3

logging:
  file:
    name: logs/admin-bff.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [traceId=%X{traceId}] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

openapi:
  title: Admin Bff API
  description: Admin Backend For Frontend API documentation
  server-url: http://localhost:9000/api/admin
  server-description: Gateway - Local

internal:
  secret: 32f9e68f9ac7ebc99d8d712ad162d78f5b7053665e143ba92a747af340b38613