pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Code checked out from GitHub'
            }
        }

        stage('Build') {
            steps {
                echo 'Build from Jenkins Pipeline'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests'
            }
        }
    }
}